"""empty message

Revision ID: 0376d2b3a149
Revises: 6eb496485113
Create Date: 2022-03-16 19:21:03.522148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0376d2b3a149'
down_revision = '6eb496485113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('review', sa.String(length=250), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'review')
    # ### end Alembic commands ###
